### ISSUE TITLE
Microsoft Defender Blocks source.exe  

### ISSUE THREAD

**Issue by Mubicool** [jere-mie/easy-masm#7]
I have been trying to use easy masm for running masm code but Microsoft Defender kept blocking it until I allowed the threat. Is there a fix to this without triggering the antivirus? Also , is it really safe to unblock it? Are the executables in lib folder authorized by Microsoft?

![image](https://github.com/jere-mie/easy-masm/assets/62619170/5b5722c1-d8ca-4bb4-8087-ba88266699e4)

**Comment by Mubicool** [comment]
Here is the attempt to run the .bat file without allowing the threat on Antivirus:
![image](https://github.com/jere-mie/easy-masm/assets/62619170/c9c8b735-fa74-4352-843c-8a0999352df3)

**Comment by jere-mie** [comment]
I don't know if there's a way to get windows defender to stop flagging easy-masm, it seems to only happen to some people. I can confirm the executables to be safe (though I don't expect you to trust a random person off the internet).

The executables were downloaded from asmdude's tutorial on using masm on windows: https://asmdude.wordpress.com/2019/02/15/how-to-install-masm32-on-windows-10/

My understanding is they're genuine executables originally from microsoft.

If you have security concerns, my recommendation is to run easy-masm in a sandbox environment like Docker or [GitHub Codespaces](https://jere-mie.github.io/easy-masm/codespaces), that way you can run it without fear or possibility of it damaging your system.

**Comment by jere-mie** [comment]
feel free to comment  further if you have any other concerns @Mubicool
